[target]
programs=samples

[compiler]
#unitdir=/home/xhermit/fpcupdeluxe/fv_utf8
#unitdir=/home/xhermit/fpcupdeluxe/fv_unicode
#unitdir=./unilib/utils
#unitdir=../../rtl-console/src/unix
#unitdir=../../rtl-unicode/src/inc
#unitdir=../../rtl-extra/src/inc
#includedir=../../rtl-console/src/inc
# includedir=./unilib/include

[default]
fpcdir=/home/xhermit/fpcupdeluxe/fpc/bin/x86_64-linux/
